project:
  type: website
  output-dir: docs

website:
  title: "Alayna Johnson"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: Projects
        menu:
          - text: Statistics Projects
            href: statistics.qmd
          - text: Data Science Projects
            href: data_visualizations.qmd
          - text: GIS Projects
            href: gis_projects.qmd
    right:
      - icon: envelope
        href: "mailto:laymariaj@gmail.com"
      - text: LinkedIn
        icon: linkedin
        href: "www.linkedin.com/in/alayna-johnson-661254256"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



